"""Investigation controls in the twelve non-English interface languages."""
ROWS='''Guided Capture|Capture guidée|Geführte Aufnahme|Acquisizione guidata|Captura guiada|Пошаговый снимок|ガイド付きキャプチャ|引导式快照|निर्देशित कैप्चर|Captura guiada|رہنمائی کے ساتھ کیپچر|নির্দেশিত ক্যাপচার|التقاط موجّه
Capture Before|Capturer avant|Vorher aufnehmen|Acquisisci prima|Capturar antes|Снимок до|変更前を保存|捕获更改前|पहले कैप्चर करें|Capturar antes|پہلے کیپچر کریں|আগের অবস্থা ক্যাপচার|التقاط الحالة قبل التغيير
Capture After|Capturer après|Nachher aufnehmen|Acquisisci dopo|Capturar después|Снимок после|変更後を保存|捕获更改后|बाद में कैप्चर करें|Capturar depois|بعد میں کیپچر کریں|পরের অবস্থা ক্যাপচার|التقاط الحالة بعد التغيير
New Experiment|Nouvelle expérience|Neues Experiment|Nuovo esperimento|Nuevo experimento|Новый эксперимент|新しい実験|新建实验|नया प्रयोग|Novo experimento|نیا تجربہ|নতুন পরীক্ষা|تجربة جديدة
Scan All Files|Analyser tous les fichiers|Alle Dateien scannen|Scansiona tutti i file|Escanear todos los archivos|Сканировать все файлы|すべてのファイルをスキャン|扫描所有文件|सभी फ़ाइलें स्कैन करें|Verificar todos os arquivos|تمام فائلیں اسکین کریں|সব ফাইল স্ক্যান করুন|فحص جميع الملفات
Save Difference Lab|Comparaison des sauvegardes|Spielstandvergleich|Confronto salvataggi|Comparador de partidas|Сравнение сохранений|セーブ比較|存档比较|सेव तुलना|Comparação de salvamentos|محفوظ گیم کا موازنہ|সেভ তুলনা|مقارنة ملفات الحفظ
Save Health / Integrity|État / Intégrité|Zustand / Integrität|Stato / Integrità|Estado / Integridad|Состояние / Целостность|セーブ状態・整合性|存档健康 / 完整性|सेव स्थिति / अखंडता|Estado / Integridade|حالت / سالمیت|সেভের অবস্থা / অখণ্ডতা|الحالة / السلامة
Field Mapping|Cartographie des champs|Feldzuordnung|Mappatura campi|Mapeo de campos|Сопоставление полей|フィールド対応|字段映射|फ़ील्ड मैपिंग|Mapeamento de campos|فیلڈ کی نقشہ بندی|ফিল্ড ম্যাপিং|تعيين الحقول
World Entities|Entités du monde|Weltobjekte|Entità del mondo|Entidades del mundo|Объекты мира|ワールド内オブジェクト|世界实体|दुनिया की इकाइयाँ|Entidades do mundo|دنیا کی اکائیاں|জগতের সত্তা|كيانات العالم
About|À propos|Über|Informazioni|Acerca de|О программе|情報|关于|परिचय|Sobre|تعارف|পরিচিতি|حول
Choose Save Root|Choisir le dossier racine|Speicherordner wählen|Scegli cartella principale|Elegir carpeta raíz|Выбрать корневую папку|セーブルートを選択|选择存档根目录|सेव मूल फ़ोल्डर चुनें|Escolher pasta raiz|بنیادی فولڈر چنیں|মূল সেভ ফোল্ডার বাছুন|اختيار مجلد الحفظ الرئيسي
Capture Snapshot A|Capturer A|Aufnahme A erstellen|Acquisisci A|Capturar A|Снять снимок A|スナップショットAを作成|创建快照 A|स्नैपशॉट A लें|Capturar A|تصویر A محفوظ کریں|স্ন্যাপশট A নিন|التقاط A
Capture Snapshot B|Capturer B|Aufnahme B erstellen|Acquisisci B|Capturar B|Снять снимок B|スナップショットBを作成|创建快照 B|स्नैपशॉट B लें|Capturar B|تصویر B محفوظ کریں|স্ন্যাপশট B নিন|التقاط B
Open A|Ouvrir A|A öffnen|Apri A|Abrir A|Открыть A|Aを開く|打开 A|A खोलें|Abrir A|A کھولیں|A খুলুন|فتح A
Open B|Ouvrir B|B öffnen|Apri B|Abrir B|Открыть B|Bを開く|打开 B|B खोलें|Abrir B|B کھولیں|B খুলুন|فتح B
Compare A / B|Comparer A / B|A / B vergleichen|Confronta A / B|Comparar A / B|Сравнить A / B|A / Bを比較|比较 A / B|A / B की तुलना|Comparar A / B|A / B کا موازنہ|A / B তুলনা করুন|مقارنة A / B
Export Difference Report|Exporter le rapport|Vergleich exportieren|Esporta confronto|Exportar comparación|Экспорт сравнения|比較レポートを出力|导出差异报告|तुलना रिपोर्ट निर्यात|Exportar comparação|موازنہ رپورٹ برآمد کریں|তুলনা প্রতিবেদন রপ্তানি|تصدير تقرير المقارنة
Evidence filters|Filtres de preuves|Belegfilter|Filtri delle prove|Filtros de evidencia|Фильтры данных|根拠フィルター|依据筛选|साक्ष्य फ़िल्टर|Filtros de evidências|شواہد کے فلٹر|প্রমাণের ফিল্টার|مرشحات الأدلة
All evidence|Toutes les preuves|Alle Belege|Tutte le prove|Toda la evidencia|Все данные|すべての根拠|全部依据|सभी साक्ष्य|Todas as evidências|تمام شواہد|সব প্রমাণ|جميع الأدلة
Known fields|Champs connus|Bekannte Felder|Campi noti|Campos conocidos|Известные поля|既知のフィールド|已知字段|ज्ञात फ़ील्ड|Campos conhecidos|معلوم فیلڈز|পরিচিত ফিল্ড|الحقول المعروفة
Unknown fields|Champs inconnus|Unbekannte Felder|Campi sconosciuti|Campos desconocidos|Неизвестные поля|未知のフィールド|未知字段|अज्ञात फ़ील्ड|Campos desconhecidos|نامعلوم فیلڈز|অজানা ফিল্ড|الحقول غير المعروفة
Added objects / fields|Objets / champs ajoutés|Neue Objekte / Felder|Oggetti / campi aggiunti|Objetos / campos añadidos|Добавленные объекты / поля|追加されたオブジェクト・フィールド|新增对象 / 字段|जोड़े गए ऑब्जेक्ट / फ़ील्ड|Objetos / campos adicionados|شامل اشیا / فیلڈز|যোগ করা অবজেক্ট / ফিল্ড|الكائنات / الحقول المضافة
Numeric changes|Changements numériques|Zahlenänderungen|Modifiche numeriche|Cambios numéricos|Изменения чисел|数値の変更|数值变化|संख्यात्मक बदलाव|Alterações numéricas|عددی تبدیلیاں|সংখ্যার পরিবর্তন|التغييرات الرقمية
Bookmarked|Favoris|Lesezeichen|Preferiti|Marcados|Закладки|ブックマーク済み|已收藏|बुकमार्क किए गए|Favoritos|بک مارک شدہ|বুকমার্ক করা|المحفوظة
Only changed files|Fichiers modifiés uniquement|Nur geänderte Dateien|Solo file modificati|Solo archivos modificados|Только изменённые файлы|変更ファイルのみ|仅显示已更改文件|केवल बदली फ़ाइलें|Só arquivos alterados|صرف تبدیل شدہ فائلیں|শুধু পরিবর্তিত ফাইল|الملفات المعدلة فقط
Toggle Bookmark|Ajouter / retirer un favori|Lesezeichen umschalten|Attiva / disattiva preferito|Alternar marcador|Добавить / убрать закладку|ブックマーク切替|切换收藏|बुकमार्क बदलें|Alternar favorito|بک مارک تبدیل کریں|বুকমার্ক চালু / বন্ধ|تبديل الإشارة المرجعية
Open Bookmarks|Ouvrir les favoris|Lesezeichen öffnen|Apri preferiti|Abrir marcadores|Открыть закладки|ブックマークを開く|打开收藏|बुकमार्क खोलें|Abrir favoritos|بک مارکس کھولیں|বুকমার্ক খুলুন|فتح الإشارات المرجعية
Open in Field Mapping|Ouvrir dans la cartographie|In Feldzuordnung öffnen|Apri nella mappatura|Abrir en mapeo de campos|Открыть сопоставление|フィールド対応で開く|在字段映射中打开|फ़ील्ड मैपिंग में खोलें|Abrir no mapeamento|فیلڈ نقشے میں کھولیں|ফিল্ড ম্যাপিংয়ে খুলুন|فتح في تعيين الحقول
Open Evidence|Ouvrir la preuve|Beleg öffnen|Apri prova|Abrir evidencia|Открыть данные|根拠を開く|打开依据|साक्ष्य खोलें|Abrir evidência|شواہد کھولیں|প্রমাণ খুলুন|فتح الدليل
Guided Experiment|Expérience guidée|Geführter Versuch|Esperimento guidato|Experimento guiado|Пошаговый эксперимент|実験ガイド|实验向导|निर्देशित प्रयोग|Experimento guiado|رہنمائی والا تجربہ|নির্দেশিত পরীক্ষা|تجربة موجهة
Save Experiment Record|Enregistrer l’expérience|Versuch speichern|Salva esperimento|Guardar experimento|Сохранить эксперимент|実験記録を保存|保存实验记录|प्रयोग रिकॉर्ड सहेजें|Salvar experimento|تجربے کا ریکارڈ محفوظ کریں|পরীক্ষার রেকর্ড সংরক্ষণ|حفظ سجل التجربة
Recipe unlock|Déblocage de recette|Rezeptfreischaltung|Sblocco ricetta|Desbloqueo de receta|Открытие рецепта|レシピ解放|配方解锁|रेसिपी अनलॉक|Desbloqueio de receita|نسخہ کھولنا|রেসিপি আনলক|فتح وصفة
Ship blueprint|Plan de vaisseau|Schiffsbauplan|Progetto nave|Plano de nave|Чертёж корабля|船の設計図|飞船蓝图|जहाज़ का नक्शा|Projeto de nave|جہاز کا نقشہ|মহাকাশযানের নকশা|مخطط سفينة
Clone validation|Validation du clone|Klonprüfung|Verifica clone|Validación del clon|Проверка копии|複製の検証|克隆验证|क्लोन सत्यापन|Validação do clone|نقل کی تصدیق|ক্লোন যাচাই|التحقق من النسخة
Qbits before|Qbits avant|Qbits vorher|Qbits prima|Qbits antes|Qbits до|変更前のQbits|更改前 Qbits|पहले Qbits|Qbits antes|پہلے Qbits|আগের Qbits|Qbits قبل
Qbits after|Qbits après|Qbits nachher|Qbits dopo|Qbits después|Qbits после|変更後のQbits|更改后 Qbits|बाद में Qbits|Qbits depois|بعد کے Qbits|পরের Qbits|Qbits بعد
Appears in game|Visible dans le jeu|Im Spiel sichtbar|Visibile nel gioco|Aparece en el juego|Виден в игре|ゲーム内に表示|在游戏中显示|गेम में दिखता है|Aparece no jogo|کھیل میں دکھائی دیتا ہے|গেমে দেখা যায়|تظهر في اللعبة
Loads successfully|Chargement réussi|Lädt erfolgreich|Caricamento riuscito|Carga correctamente|Успешно загружается|正常に読み込める|成功加载|सफलतापूर्वक लोड होता है|Carrega corretamente|کامیابی سے لوڈ ہوتا ہے|সফলভাবে লোড হয়|تُحمّل بنجاح
Saves independently|Sauvegarde indépendante|Speichert unabhängig|Salva indipendentemente|Guarda independientemente|Сохраняется независимо|独立して保存できる|独立保存|स्वतंत्र रूप से सेव होता है|Salva independentemente|الگ سے محفوظ ہوتا ہے|স্বতন্ত্রভাবে সেভ হয়|تُحفظ بشكل مستقل
Survives game restart|Conservé après redémarrage|Bleibt nach Neustart erhalten|Persiste dopo il riavvio|Persiste al reiniciar|Сохраняется после перезапуска|再起動後も保持|重启游戏后仍保留|गेम पुनः शुरू होने पर बना रहता है|Persiste após reiniciar|دوبارہ شروع کرنے پر برقرار|গেম পুনরায় চালু হলেও থাকে|تبقى بعد إعادة تشغيل اللعبة
Original slot unchanged|Original inchangé|Original unverändert|Originale invariato|Original sin cambios|Оригинал не изменён|元のスロットに変更なし|原存档槽未更改|मूल स्लॉट अपरिवर्तित|Original inalterado|اصل سلاٹ غیر تبدیل شدہ|মূল স্লট অপরিবর্তিত|الخانة الأصلية دون تغيير
Scan Save Health|Vérifier l’intégrité|Spielstand prüfen|Verifica integrità|Comprobar integridad|Проверить сохранение|整合性を検査|扫描存档完整性|सेव की जाँच करें|Verificar integridade|محفوظ گیم جانچیں|সেভের অখণ্ডতা পরীক্ষা|فحص سلامة الحفظ
Recover Interrupted Transactions|Récupérer les opérations interrompues|Unterbrochene Vorgänge wiederherstellen|Recupera operazioni interrotte|Recuperar operaciones interrumpidas|Восстановить прерванные операции|中断された処理を復元|恢复中断的事务|अधूरे लेनदेन बहाल करें|Recuperar operações interrompidas|نامکمل کارروائیاں بحال کریں|বাধাপ্রাপ্ত কাজ পুনরুদ্ধার|استعادة العمليات المتوقفة
Clone Selected Slot|Cloner l’emplacement|Gewählten Spielstand klonen|Clona slot selezionato|Clonar ranura seleccionada|Клонировать выбранный слот|選択スロットを複製|克隆所选存档槽|चुना स्लॉट क्लोन करें|Clonar slot selecionado|منتخب سلاٹ نقل کریں|নির্বাচিত স্লট ক্লোন করুন|استنساخ الخانة المحددة
Scan Fields Across Slots|Comparer les champs des emplacements|Felder aller Spielstände prüfen|Analizza campi degli slot|Analizar campos de las ranuras|Просканировать поля слотов|全スロットのフィールドを検査|扫描各存档槽字段|सभी स्लॉट के फ़ील्ड जाँचें|Analisar campos dos slots|تمام سلاٹ کے فیلڈز جانچیں|সব স্লটের ফিল্ড পরীক্ষা|فحص الحقول عبر الخانات
Edit Known Field|Modifier le champ connu|Bekanntes Feld bearbeiten|Modifica campo noto|Editar campo conocido|Изменить известное поле|既知フィールドを編集|编辑已知字段|ज्ञात फ़ील्ड संपादित करें|Editar campo conhecido|معلوم فیلڈ میں ترمیم|পরিচিত ফিল্ড সম্পাদনা|تحرير الحقل المعروف
Save Mapping Evidence|Enregistrer la preuve|Zuordnungsbeleg speichern|Salva prove della mappatura|Guardar evidencia del mapeo|Сохранить доказательства|対応の根拠を保存|保存映射依据|मैपिंग साक्ष्य सहेजें|Salvar evidências do mapeamento|نقشہ بندی کے شواہد محفوظ کریں|ম্যাপিংয়ের প্রমাণ সংরক্ষণ|حفظ أدلة التعيين
Scan / Filter Entities|Analyser / filtrer les entités|Objekte prüfen / filtern|Analizza / filtra entità|Analizar / filtrar entidades|Сканировать / фильтровать объекты|オブジェクトを検査・絞込|扫描 / 筛选实体|इकाइयाँ जाँचें / छाँटें|Analisar / filtrar entidades|اکائیاں جانچیں / چھانٹیں|সত্তা পরীক্ষা / ফিল্টার|فحص / تصفية الكيانات
Edit Contained Quantity|Modifier la quantité contenue|Enthaltene Menge bearbeiten|Modifica quantità contenuta|Editar cantidad contenida|Изменить количество внутри|内容物の数量を編集|编辑容器内数量|अंदर की मात्रा बदलें|Editar quantidade contida|اندر کی مقدار تبدیل کریں|ভিতরের পরিমাণ সম্পাদনা|تحرير الكمية المحتواة
Edit Contained Condition|Modifier l’état contenu|Enthaltenen Zustand bearbeiten|Modifica condizione contenuta|Editar estado del contenido|Изменить состояние внутри|内容物の状態を編集|编辑容器内状态|अंदर की स्थिति बदलें|Editar condição contida|اندر کی حالت تبدیل کریں|ভিতরের অবস্থা সম্পাদনা|تحرير حالة المحتوى
Stage New Item|Préparer le nouvel objet|Neuen Gegenstand vormerken|Prepara nuovo oggetto|Preparar nuevo objeto|Подготовить новый предмет|新規アイテムを保留|暂存新物品|नई वस्तु तैयार करें|Preparar novo item|نئی شے تیار کریں|নতুন আইটেম প্রস্তুত করুন|تجهيز عنصر جديد
Stage Character Vitals|Préparer l’état du personnage|Charakterzustand vormerken|Prepara condizioni personaggio|Preparar estado del personaje|Подготовить состояние персонажа|キャラクター状態を保留|暂存角色状态|पात्र की स्थिति तैयार करें|Preparar condição do personagem|کردار کی حالت تیار کریں|চরিত্রের অবস্থা প্রস্তুত করুন|تجهيز حالة الشخصية
Stage Character Skills|Préparer les compétences|Fähigkeiten vormerken|Prepara abilità|Preparar habilidades|Подготовить навыки|スキル変更を保留|暂存角色技能|पात्र के कौशल तैयार करें|Preparar habilidades|کردار کی مہارتیں تیار کریں|চরিত্রের দক্ষতা প্রস্তুত করুন|تجهيز مهارات الشخصية
Stage Class Levels|Préparer les niveaux de classe|Klassenstufen vormerken|Prepara livelli classe|Preparar niveles de clase|Подготовить уровни классов|クラスレベルを保留|暂存职业等级|वर्ग स्तर तैयार करें|Preparar níveis de classe|کلاس کی سطحیں تیار کریں|শ্রেণির স্তর প্রস্তুত করুন|تجهيز مستويات الفئات
Stage Display Name|Préparer le nom|Anzeigenamen vormerken|Prepara nome|Preparar nombre|Подготовить имя|表示名を保留|暂存显示名称|प्रदर्शित नाम तैयार करें|Preparar nome|ظاہری نام تیار کریں|প্রদর্শিত নাম প্রস্তুত করুন|تجهيز اسم العرض
Review / Stage|Vérifier / Préparer|Prüfen / Vormerken|Rivedi / Prepara|Revisar / Preparar|Проверить / Подготовить|確認・保留|检查 / 暂存|समीक्षा / तैयार करें|Revisar / Preparar|جائزہ / تیار کریں|পর্যালোচনা / প্রস্তুত|مراجعة / تجهيز
Ready|Prêt|Bereit|Pronto|Listo|Готово|準備完了|就绪|तैयार|Pronto|تیار|প্রস্তুত|جاهز
Complete|Terminé|Abgeschlossen|Completato|Completado|Завершено|完了|完成|पूर्ण|Concluído|مکمل|সম্পন্ন|مكتمل
Capturing|Capture|Aufnahme|Acquisizione|Capturando|Создание снимка|取得中|正在捕获|कैप्चर जारी|Capturando|محفوظ ہو رہا ہے|ধারণ করা হচ্ছে|جارٍ الالتقاط
Verifying|Vérification|Überprüfung|Verifica|Verificando|Проверка|検証中|正在验证|जाँच जारी|Verificando|جانچ جاری ہے|যাচাই করা হচ্ছে|جارٍ التحقق
Comparing|Comparaison|Vergleich|Confronto|Comparando|Сравнение|比較中|正在比较|तुलना जारी|Comparando|موازنہ جاری ہے|তুলনা করা হচ্ছে|جارٍ المقارنة
Copying|Copie|Kopieren|Copia|Copiando|Копирование|コピー中|正在复制|प्रतिलिपि जारी|Copiando|نقل جاری ہے|কপি করা হচ্ছে|جارٍ النسخ
Operation failed|Échec de l’opération|Vorgang fehlgeschlagen|Operazione non riuscita|La operación falló|Ошибка операции|処理に失敗|操作失败|कार्रवाई विफल|Falha na operação|کارروائی ناکام|কাজ ব্যর্থ|فشلت العملية
Working|En cours|In Arbeit|In corso|En curso|Выполняется|処理中|处理中|कार्य जारी|Em andamento|کام جاری ہے|কাজ চলছে|جارٍ العمل
Evidence|Preuve|Beleg|Prova|Evidencia|Данные|根拠|依据|साक्ष्य|Evidência|شواہد|প্রমাণ|الدليل
Snapshot|Capture|Aufnahme|Istantanea|Captura|Снимок|スナップショット|快照|स्नैपशॉट|Captura|تصویر|স্ন্যাপশট|لقطة
Unknown|Inconnu|Unbekannt|Sconosciuto|Desconocido|Неизвестно|不明|未知|अज्ञात|Desconhecido|نامعلوم|অজানা|غير معروف
Suspected|Supposé|Vermutet|Ipotizzato|Supuesto|Предполагается|推定|推测|अनुमानित|Suspeito|مشتبہ|অনুমিত|مفترض
Verified|Vérifié|Bestätigt|Verificato|Verificado|Подтверждено|確認済み|已验证|सत्यापित|Verificado|تصدیق شدہ|যাচাইকৃত|تم التحقق
Healthy|Sain|In Ordnung|Integro|Correcto|Исправно|正常|健康|स्वस्थ|Íntegro|درست|সুস্থ|سليم
Warning|Avertissement|Warnung|Avviso|Advertencia|Предупреждение|警告|警告|चेतावनी|Aviso|انتباہ|সতর্কতা|تحذير
Failed|Échec|Fehlgeschlagen|Non valido|Fallido|Ошибка|失敗|失败|विफल|Falha|ناکام|ব্যর্থ|فشل
Added|Ajouté|Hinzugefügt|Aggiunto|Añadido|Добавлено|追加|已新增|जोड़ा गया|Adicionado|شامل شدہ|যোগ হয়েছে|مضاف
Removed|Supprimé|Entfernt|Rimosso|Eliminado|Удалено|削除|已移除|हटाया गया|Removido|ہٹایا گیا|সরানো হয়েছে|محذوف
Changed|Modifié|Geändert|Modificato|Modificado|Изменено|変更|已更改|बदला गया|Alterado|تبدیل شدہ|পরিবর্তিত|معدل
Unchanged|Inchangé|Unverändert|Invariato|Sin cambios|Без изменений|変更なし|未更改|अपरिवर्तित|Inalterado|غیر تبدیل شدہ|অপরিবর্তিত|دون تغيير'''
TRANSLATIONS={}
ROWS+='''
Scanning|Analyse|Prüfung|Analisi|Analizando|Сканирование|検査中|正在扫描|स्कैन जारी|Analisando|جانچ جاری ہے|স্ক্যান চলছে|جارٍ الفحص
Recording experiment|Enregistrement de l’expérience|Versuch wird gespeichert|Registrazione esperimento|Registrando experimento|Запись эксперимента|実験を記録中|正在记录实验|प्रयोग दर्ज हो रहा है|Registrando experimento|تجربہ درج ہو رہا ہے|পরীক্ষা নথিভুক্ত হচ্ছে|جارٍ تسجيل التجربة
Serializer path|Chemin du champ|Serialisierungspfad|Percorso campo|Ruta del campo|Путь поля|フィールドパス|序列化路径|फ़ील्ड पथ|Caminho do campo|فیلڈ کا راستہ|ফিল্ডের পথ|مسار الحقل
Known name|Nom connu|Bekannter Name|Nome noto|Nombre conocido|Известное имя|既知の名前|已知名称|ज्ञात नाम|Nome conhecido|معلوم نام|পরিচিত নাম|الاسم المعروف
Observed value|Valeur observée|Beobachteter Wert|Valore osservato|Valor observado|Наблюдаемое значение|観測値|观测值|देखा गया मान|Valor observado|مشاہدہ شدہ قدر|পর্যবেক্ষিত মান|القيمة المرصودة
Research status|État de recherche|Forschungsstatus|Stato ricerca|Estado de investigación|Статус исследования|調査状態|研究状态|अनुसंधान स्थिति|Estado da pesquisa|تحقیق کی حالت|গবেষণার অবস্থা|حالة البحث
Field / offset|Champ / position|Feld / Offset|Campo / posizione|Campo / posición|Поле / смещение|フィールド・位置|字段 / 偏移|फ़ील्ड / ऑफ़सेट|Campo / posição|فیلڈ / مقام|ফিল্ড / অফসেট|الحقل / الإزاحة
World file|Fichier du monde|Weltdatei|File del mondo|Archivo del mundo|Файл мира|ワールドファイル|世界文件|दुनिया की फ़ाइल|Arquivo do mundo|دنیا کی فائل|জগতের ফাইল|ملف العالم
Category hint|Catégorie supposée|Kategoriehinweis|Categoria indicativa|Categoría orientativa|Предполагаемая категория|推定分類|类别提示|अनुमानित श्रेणी|Categoria indicativa|زمرے کا اشارہ|অনুমিত বিভাগ|تلميح الفئة
Entity ID|ID d’entité|Objekt-ID|ID entità|ID de entidad|ID объекта|オブジェクトID|实体 ID|इकाई ID|ID da entidade|اکائی ID|সত্তার ID|معرّف الكيان
Saved kind|Type enregistré|Gespeicherter Typ|Tipo salvato|Tipo guardado|Сохранённый тип|保存された種類|保存的类型|सहेजा प्रकार|Tipo salvo|محفوظ قسم|সংরক্ষিত ধরন|النوع المحفوظ
Validation|Validation|Prüfung|Verifica|Validación|Проверка|検証|验证|सत्यापन|Validação|تصدیق|যাচাই|التحقق
Status|État|Status|Stato|Estado|Статус|状態|状态|स्थिति|Estado|حالت|অবস্থা|الحالة
Date|Date|Datum|Data|Fecha|Дата|日付|日期|तारीख|Data|تاریخ|তারিখ|التاريخ
Note|Note|Hinweis|Nota|Nota|Примечание|注記|备注|टिप्पणी|Nota|نوٹ|টীকা|ملاحظة
Error|Erreur|Fehler|Errore|Error|Ошибка|エラー|错误|त्रुटि|Erro|خرابی|ত্রুটি|خطأ
Source evidence and in-game observations|Preuves et observations en jeu|Quellen und Beobachtungen im Spiel|Fonti e osservazioni nel gioco|Fuentes y observaciones en el juego|Источники и наблюдения в игре|出典とゲーム内の観測|来源依据与游戏内观察|स्रोत साक्ष्य और गेम के अवलोकन|Fontes e observações no jogo|ماخذ کے شواہد اور کھیل کے مشاہدات|উৎসের প্রমাণ ও গেমের পর্যবেক্ষণ|الأدلة المصدرية والملاحظات داخل اللعبة
Action / recipe / blueprint / clone path|Action / recette / plan / chemin du clone|Aktion / Rezept / Bauplan / Klonpfad|Azione / ricetta / progetto / percorso clone|Acción / receta / plano / ruta del clon|Действие / рецепт / чертёж / путь копии|操作・レシピ・設計図・複製パス|操作 / 配方 / 蓝图 / 克隆路径|कार्य / रेसिपी / नक्शा / क्लोन पथ|Ação / receita / projeto / caminho do clone|عمل / نسخہ / نقشہ / نقل کا راستہ|কাজ / রেসিপি / নকশা / ক্লোনের পথ|الإجراء / الوصفة / المخطط / مسار النسخة
Clone checks — tick only results you observed in-game.|Clone : cochez seulement les résultats observés en jeu.|Klon: nur im Spiel beobachtete Ergebnisse markieren.|Clone: seleziona solo risultati osservati nel gioco.|Clon: marca solo resultados observados en el juego.|Копия: отметьте только результаты, наблюдавшиеся в игре.|複製：ゲーム内で確認した結果のみチェック。|克隆检查：仅勾选游戏内实际观察到的结果。|क्लोन जाँच: केवल गेम में देखे परिणाम चुनें।|Clone: marque apenas resultados observados no jogo.|نقل: صرف کھیل میں دیکھے گئے نتائج نشان زد کریں۔|ক্লোন: শুধু গেমে দেখা ফলাফল চিহ্নিত করুন।|النسخة: حدد فقط النتائج التي شاهدتها داخل اللعبة.
Additional observations / repeat experiment / in-game result|Autres observations / répétition / résultat en jeu|Weitere Beobachtungen / Wiederholung / Spielergebnis|Altre osservazioni / ripetizione / risultato nel gioco|Observaciones adicionales / repetición / resultado en el juego|Другие наблюдения / повтор / результат в игре|追加の観測・再実験・ゲーム内の結果|补充观察 / 重复实验 / 游戏内结果|अतिरिक्त अवलोकन / दोहराया प्रयोग / गेम का परिणाम|Outras observações / repetição / resultado no jogo|مزید مشاہدات / دوبارہ تجربہ / کھیل کا نتیجہ|অতিরিক্ত পর্যবেক্ষণ / পুনরাবৃত্তি / গেমের ফলাফল|ملاحظات إضافية / تكرار التجربة / النتيجة داخل اللعبة
Close the game for each capture. Select the account save root to include global files.|Fermez le jeu pour chaque capture. Sélectionnez la racine des sauvegardes du compte pour inclure les fichiers globaux.|Spiel vor jeder Aufnahme schließen. Kontospeicherordner wählen, um globale Dateien einzuschließen.|Chiudi il gioco per ogni acquisizione. Scegli la cartella del conto per includere i file globali.|Cierra el juego para cada captura. Elige la raíz de guardados de la cuenta para incluir archivos globales.|Закрывайте игру перед каждым снимком. Выберите корень сохранений аккаунта, включая глобальные файлы.|毎回ゲームを終了して取得してください。グローバルファイルを含むアカウントのセーブルートを選択します。|每次捕获前关闭游戏。选择账户存档根目录以包含全局文件。|हर कैप्चर से पहले गेम बंद करें। वैश्विक फ़ाइलों के लिए खाते का मूल सेव फ़ोल्डर चुनें।|Feche o jogo a cada captura. Escolha a raiz dos salvamentos da conta para incluir arquivos globais.|ہر تصویر سے پہلے کھیل بند کریں۔ عالمی فائلوں کے لیے اکاؤنٹ کا بنیادی محفوظ فولڈر چنیں۔|প্রতিটি ক্যাপচারের আগে গেম বন্ধ করুন। গ্লোবাল ফাইলসহ অ্যাকাউন্টের মূল সেভ ফোল্ডার বাছুন।|أغلق اللعبة لكل لقطة. اختر مجلد حفظ الحساب الرئيسي لتضمين الملفات العامة.
Healthy means available checks passed. Unknown formats receive partial validation.|Sain signifie que les contrôles disponibles ont réussi. Les formats inconnus ne sont validés que partiellement.|In Ordnung bedeutet: verfügbare Prüfungen bestanden. Unbekannte Formate werden nur teilweise geprüft.|Integro indica controlli disponibili superati. I formati sconosciuti sono verificati solo in parte.|Correcto significa que superó las comprobaciones disponibles. Los formatos desconocidos se validan parcialmente.|Исправно означает прохождение доступных проверок. Неизвестные форматы проверяются частично.|正常は利用可能な検査に合格した意味です。未知の形式は部分的な検証のみです。|健康表示已通过现有检查。未知格式仅进行部分验证。|स्वस्थ का अर्थ उपलब्ध जाँच सफल हैं। अज्ञात प्रारूपों की आंशिक जाँच होती है।|Íntegro significa que passou nas verificações disponíveis. Formatos desconhecidos têm validação parcial.|درست کا مطلب دستیاب جانچیں کامیاب ہیں۔ نامعلوم فارمیٹ کی جزوی تصدیق ہوتی ہے۔|সুস্থ মানে উপলব্ধ পরীক্ষাগুলো পাস করেছে। অজানা ফরম্যাট আংশিক যাচাই হয়।|سليم يعني اجتياز الفحوص المتاحة. الصيغ غير المعروفة تُفحص جزئياً.
Record field evidence across slots. Only known fields have validated writers.|Notez les preuves des champs entre emplacements. Seuls les champs connus ont une écriture validée.|Feldbelege über Spielstände erfassen. Nur bekannte Felder besitzen geprüfte Schreibfunktionen.|Registra prove dei campi tra slot. Solo i campi noti hanno scrittura verificata.|Registra evidencia de campos entre ranuras. Solo los campos conocidos tienen escritura validada.|Записывайте данные полей разных слотов. Проверенная запись доступна только известным полям.|スロット間のフィールド根拠を記録します。検証済みの書き込みは既知フィールドのみです。|记录各存档槽的字段依据。仅已知字段具有经过验证的写入功能。|स्लॉटों में फ़ील्ड के साक्ष्य दर्ज करें। केवल ज्ञात फ़ील्ड के लेखन सत्यापित हैं।|Registre evidências dos campos entre slots. Só campos conhecidos têm escrita validada.|سلاٹوں کے فیلڈ شواہد درج کریں۔ صرف معلوم فیلڈز کے لیے تصدیق شدہ تحریر ہے۔|স্লটগুলোর ফিল্ডের প্রমাণ নথিভুক্ত করুন। শুধু পরিচিত ফিল্ডে যাচাইকৃত লেখা যায়।|سجل أدلة الحقول عبر الخانات. الكتابة المعتمدة متاحة للحقول المعروفة فقط.
Inspect world objects and edit supported contained items. Other entity state is read-only.|Inspectez les objets du monde et modifiez les objets contenus pris en charge. Les autres états sont en lecture seule.|Weltobjekte prüfen und unterstützte Inhalte bearbeiten. Andere Objektzustände sind schreibgeschützt.|Esamina oggetti del mondo e modifica contenuti supportati. Gli altri stati sono di sola lettura.|Inspecciona objetos y edita contenidos compatibles. El resto del estado es de solo lectura.|Просматривайте объекты мира и меняйте поддерживаемые предметы внутри. Остальные состояния доступны только для чтения.|ワールドのオブジェクトを検査し、対応する内容物を編集します。その他の状態は閲覧のみです。|查看世界对象并编辑支持的容器内物品。其他实体状态为只读。|दुनिया की वस्तुएँ देखें और समर्थित सामग्री बदलें। अन्य इकाई स्थितियाँ केवल पढ़ी जा सकती हैं।|Inspecione objetos e edite conteúdos compatíveis. Outros estados são somente leitura.|دنیا کی اشیا دیکھیں اور معاون اندرونی سامان بدلیں۔ باقی حالت صرف پڑھنے کے لیے ہے۔|জগতের অবজেক্ট দেখুন ও সমর্থিত ভেতরের আইটেম বদলান। অন্য অবস্থা শুধু পড়া যায়।|افحص كائنات العالم وحرر المحتويات المدعومة. الحالات الأخرى للكيانات للقراءة فقط.
Capture A, perform one action in-game, then capture B. Record your observations.|Capturez A, effectuez une seule action en jeu, puis capturez B. Notez vos observations.|A aufnehmen, genau eine Spielaktion ausführen, dann B aufnehmen. Beobachtungen notieren.|Acquisisci A, esegui una sola azione nel gioco, poi acquisisci B. Registra le osservazioni.|Captura A, realiza una acción en el juego y captura B. Registra tus observaciones.|Снимите A, выполните одно действие в игре, затем снимите B. Запишите наблюдения.|Aを取得し、ゲーム内で1つ操作してからBを取得します。観測結果を記録してください。|捕获 A，在游戏中执行一个操作，然后捕获 B。记录观察结果。|A कैप्चर करें, गेम में एक कार्य करें, फिर B कैप्चर करें। अपने अवलोकन दर्ज करें।|Capture A, faça uma ação no jogo e capture B. Registre suas observações.|A محفوظ کریں، کھیل میں ایک عمل کریں، پھر B محفوظ کریں۔ مشاہدات درج کریں۔|A নিন, গেমে একটি কাজ করুন, তারপর B নিন। পর্যবেক্ষণ লিখুন।|التقط A، نفذ إجراءً واحداً في اللعبة، ثم التقط B. سجل ملاحظاتك.
Please wait for the current operation.|Veuillez attendre la fin de l’opération.|Bitte den aktuellen Vorgang abwarten.|Attendi l’operazione corrente.|Espera a que termine la operación.|Дождитесь завершения операции.|現在の処理が終わるまでお待ちください。|请等待当前操作完成。|वर्तमान कार्य पूरा होने दें।|Aguarde a operação atual.|موجودہ کارروائی مکمل ہونے دیں۔|বর্তমান কাজ শেষ হওয়া পর্যন্ত অপেক্ষা করুন।|يرجى انتظار انتهاء العملية الحالية.
Choose both snapshots first.|Choisissez d’abord les deux captures.|Zuerst beide Aufnahmen wählen.|Scegli prima entrambe le acquisizioni.|Elige primero ambas capturas.|Сначала выберите оба снимка.|先に両方のスナップショットを選択してください。|请先选择两个快照。|पहले दोनों स्नैपशॉट चुनें।|Escolha primeiro as duas capturas.|پہلے دونوں تصاویر چنیں۔|আগে দুটি স্ন্যাপশট বাছুন।|اختر اللقطتين أولاً.
Snapshot evidence is read-only. Scan live fields to edit a supported value.|Les preuves des captures sont en lecture seule. Analysez les fichiers actifs pour modifier une valeur prise en charge.|Aufnahmebelege sind schreibgeschützt. Aktuelle Felder prüfen, um unterstützte Werte zu bearbeiten.|Le prove delle acquisizioni sono di sola lettura. Analizza i campi attuali per modificare un valore supportato.|La evidencia de capturas es de solo lectura. Analiza los campos actuales para editar valores compatibles.|Данные снимка доступны только для чтения. Для правки поддерживаемого значения просканируйте текущие поля.|スナップショットの根拠は閲覧専用です。対応する値を編集するには現在のフィールドを検査してください。|快照依据为只读。请扫描当前字段以编辑支持的值。|स्नैपशॉट साक्ष्य केवल पढ़ने योग्य हैं। समर्थित मान बदलने के लिए वर्तमान फ़ील्ड स्कैन करें।|Evidências de capturas são somente leitura. Analise campos atuais para editar valores compatíveis.|تصویر کے شواہد صرف پڑھنے کے لیے ہیں۔ معاون قدر بدلنے کے لیے موجودہ فیلڈز جانچیں۔|স্ন্যাপশটের প্রমাণ শুধু পড়া যায়। সমর্থিত মান বদলাতে বর্তমান ফিল্ড স্ক্যান করুন।|أدلة اللقطة للقراءة فقط. افحص الحقول الحالية لتعديل قيمة مدعومة.'''
for row in ROWS.splitlines():
    key,*values=row.split('|')
    if len(values)!=12:raise ValueError('Translation row: '+key)
    TRANSLATIONS[key]=values

TRANSLATIONS.update({'Choose File': ['Choisir un fichier', 'Datei wählen', 'Scegli file', 'Elegir archivo', 'Выбрать файл', 'ファイルを選択', '选择文件', 'फ़ाइल चुनें', 'Escolher arquivo', 'فائل چنیں', 'ফাইল বাছুন', 'اختيار ملف'], 'Choose Folder': ['Choisir un dossier', 'Ordner wählen', 'Scegli cartella', 'Elegir carpeta', 'Выбрать папку', 'フォルダーを選択', '选择文件夹', 'फ़ोल्डर चुनें', 'Escolher pasta', 'فولڈر چنیں', 'ফোল্ডার বাছুন', 'اختيار مجلد'], 'Choose both inputs first.': ['Choisissez d’abord les deux sources.', 'Zuerst beide Quellen wählen.', 'Scegli prima entrambe le fonti.', 'Elige primero ambas entradas.', 'Сначала выберите оба источника.', '先に両方の入力を選択してください。', '请先选择两个输入。', 'पहले दोनों स्रोत चुनें।', 'Escolha primeiro as duas fontes.', 'پہلے دونوں ذرائع چنیں۔', 'আগে দুটি উৎস বাছুন।', 'اختر المصدرين أولاً.'], 'Changed files': ['Fichiers modifiés', 'Geänderte Dateien', 'File modificati', 'Archivos modificados', 'Изменённые файлы', '変更されたファイル', '已更改文件', 'बदली फ़ाइलें', 'Arquivos alterados', 'تبدیل شدہ فائلیں', 'পরিবর্তিত ফাইল', 'الملفات المعدلة'], 'No differences found.': ['Aucune différence trouvée.', 'Keine Unterschiede gefunden.', 'Nessuna differenza trovata.', 'No se encontraron diferencias.', 'Различий не найдено.', '差分は見つかりませんでした。', '未发现差异。', 'कोई अंतर नहीं मिला।', 'Nenhuma diferença encontrada.', 'کوئی فرق نہیں ملا۔', 'কোনো পার্থক্য পাওয়া যায়নি।', 'لم يتم العثور على اختلافات.'], 'Choose File A': ['Choisir un fichier A', 'Datei wählen A', 'Scegli file A', 'Elegir archivo A', 'Выбрать файл A', 'ファイルを選択 A', '选择文件 A', 'फ़ाइल चुनें A', 'Escolher arquivo A', 'فائل چنیں A', 'ফাইল বাছুন A', 'اختيار ملف A'], 'Choose File B': ['Choisir un fichier B', 'Datei wählen B', 'Scegli file B', 'Elegir archivo B', 'Выбрать файл B', 'ファイルを選択 B', '选择文件 B', 'फ़ाइल चुनें B', 'Escolher arquivo B', 'فائل چنیں B', 'ফাইল বাছুন B', 'اختيار ملف B'], 'Choose Folder A': ['Choisir un dossier A', 'Ordner wählen A', 'Scegli cartella A', 'Elegir carpeta A', 'Выбрать папку A', 'フォルダーを選択 A', '选择文件夹 A', 'फ़ोल्डर चुनें A', 'Escolher pasta A', 'فولڈر چنیں A', 'ফোল্ডার বাছুন A', 'اختيار مجلد A'], 'Choose Folder B': ['Choisir un dossier B', 'Ordner wählen B', 'Scegli cartella B', 'Elegir carpeta B', 'Выбрать папку B', 'フォルダーを選択 B', '选择文件夹 B', 'फ़ोल्डर चुनें B', 'Escolher pasta B', 'فولڈر چنیں B', 'ফোল্ডার বাছুন B', 'اختيار مجلد B']})
